### ISSUE TITLE
Add new methods for pagenumber,line number, etc

### ISSUE THREAD

**Issue by leslyarun** [codeborne/pdf-test#1]
Pls add methods for finding pagenumber in pdf, linenumber

Pls provide the maven code for using pdf-test

**Comment by asolntsev** [comment]
<dependency>
    <groupId>com.codeborne</groupId>
    <artifactId>pdf-test</artifactId>
    <version>1.2</version>
  </dependency>

**Comment by asolntsev** [comment]
@leslyarun Hi! What did you mean by "methods for finding pagenumber in pdf, linenumber"? What exactly do you want to verify in PDF?

Here is the maven code:

```xml
<dependency>
    <groupId>com.codeborne</groupId>
    <artifactId>pdf-test</artifactId>
    <version>1.5.0</version>
</dependency>
```
