### ISSUE TITLE
I've got "Invalid PDF" when parsing PDF which was concatenated using two PDF files

### ISSUE THREAD

**Issue by iHalych** [codeborne/pdf-test#2]
After passing this file 
[PO_US-14602_1521108736.pdf](https://github.com/codeborne/pdf-test/files/1818684/PO_US-14602_1521108736.pdf) I'm receiving "Invalid PDF" exception

It works just fine if I pass only first page (which is first concantenated PDF) 
[PO_11179_1520159715.pdf](https://github.com/codeborne/pdf-test/files/1818692/PO_11179_1520159715.pdf)

**Comment by asolntsev** [comment]
@iHalych it was a bug of apache pdfbox. Upgrade to PDFBox 2.0.9 helped.
Please try to upgrade to `pdf-test 1.5.0`
