### ISSUE TITLE
Please add the ability to start checking from a specific page or on a specific page of the document.

### ISSUE THREAD

**Issue by VitalyShalaev** [codeborne/pdf-test#4]
I know that it is possible to start checking from a specific page in org.apache.pdfbox:
PDFTextStripper pdfStrip = new PDFTextStripper();
pdfStrip.setStartPage(2);
String content = pdfStrip.getText(doc);

But it would be nice to add the ability to take text only from a certain number of the page, I can tell you about this on a separate issue if necessary.

UPD: the end can be set like this
pdfStrip.setEndPage(2);

**Comment by asolntsev** [comment]
@VitalyShalaev Just released the fix as version 1.6.0
